on: push
name: Test and Lint

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: ./scripts/test.sh
