on: push
name: Test and Lint

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: ./scripts/test.sh
      - name: Aggregate coverage reports
        run: node scripts/aggregate-coverage.js
      - name: Publish coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage.json
          token: ${{ secrets.CODECOV_TOKEN }}

